### ISSUE TITLE
Not Wokring

### ISSUE THREAD

**Issue by Ashura1996** [Nik-Potokar/Astro#1]
I cant install it how ever i used the same URL that i used before ...did i do anthing wrong?

**Comment by Nik-Potokar** [comment]
There is no url ATM if you want to use the updated version you got to download it from the releases and put it into the dev plugins manually.

That's will be the case for now until the original owner replies or if he dosent reply soon I will have a link that you can use to install it.

But for now you have to install manually because I don't want to take the original creators credit.

Installing manually and removing the old Astro plugin will work.

The plugin will appear under dev plugins in-game after you add it and it's path into dalamud.

**Comment by Ashura1996** [comment]
Thanks for the Quick response  :) i hope u will get a quick anser from the OWner of this Plugin ,  maybe it sounds stupid but i acutally did this but it says falining to loade..

**Comment by Nik-Potokar** [comment]
Have you removed the old plugin and it's settings in pluginconfigs?
Try that

**Comment by Ashura1996** [comment]
Yeah i did but maybe i just didnt insert it to the right coz its still not Wokring  maybe u can tell me the right direction ? :c and Thanks in Advance for ur Help!

**Comment by Nik-Potokar** [comment]
You download the ZIP file from the release [Here](https://github.com/Nik-Potokar/Astro/releases/tag/Latest)
Then you open the file and inside should be a folder called astro
You press Windows key + R to open the command menu
Type in %appdata%
Look for xivlauncher
then look for dev plugins
and drop the astro folder inside it
You go ingame and open dalamud settings and experimental tab
Add the path to the dalamud under dev path in my case its "C:\Users\YourPCName\AppData\Roaming\XIVLauncher\devPlugins"
Then add it and press save
Click on search dev plugins in the plugin selection window
A new section should appear where you see Installed/All plugins called DevPlugins
and from there you can enable it and it should work

**Comment by Ashura1996** [comment]
Thank u very very much! its working now! i appreciate ur help ! really ur the best men! also thnaks for the quick and helpfull Response!

**Comment by Nik-Potokar** [comment]
No problem glad to hear that is working
