### ISSUE TITLE
6.3 update?

### ISSUE THREAD

**Issue by Ants1988** [Nik-Potokar/Astro#4]
Is there plans to update this for 6.3?

Makes playing AST so much easier.

**Comment by Nik-Potokar** [comment]
I'm currently testing the update (checking if i got all the offsets correct) and if so il have an update out in a bit

**Comment by Nik-Potokar** [comment]
Update should be up!
Let me know if you come across any issues

**Comment by Ants1988** [comment]
I'll run a few roulettes after breakfast and report back.

**Comment by Niahmie** [comment]
> Update should be up! Let me know if you come across any issues

Hi there, for some reason for me, it's reporting my plugin as being out of date since 6.3, with no option to update it. I have it installed from the repo link: https://raw.githubusercontent.com/Nik-Potokar/Plogons/main/pluginmaster.json

Any idea what could be causing this? All the other plugins I use are fine. Any help would be greatly appreciated

**Comment by Nik-Potokar** [comment]
Try deleting the repo link and then deleting the plugin from %appdata%/xivlauncher/installed plugins or if you happen to have it manually installed in the dev plugins.

Then restart the game and re add the repo link and it should how the correct version.

If none of that works if you dm me on the discord I can give you the plugin file or download it from the link inside the repo link.

https://github.com/Nik-Potokar/Plogons/raw/main/Plugins/Astro/Astro.zip

**Comment by Niahmie** [comment]
That worked perfectly for me, thank you so much the help and quick response. This plugin is very much appreciated, I'm grateful to the creator and to you for updating it.

**Comment by Nik-Potokar** [comment]
Glad you got it working!
